#!/usr/bin/env python3
"""
add-related-adrs.py — one-time batch script

Adds a "## Related Architecture Decisions" section to each applicable
artifact template that doesn't already have one. The section is inserted
before the Appendix A3 or A4 block (or at the end of the file if neither
appendix is present).

Run from the repo root:
    python ea-assistant/scripts/add-related-adrs.py

Dry run (no file writes):
    python ea-assistant/scripts/add-related-adrs.py --dry-run
"""

import sys
import re
from pathlib import Path

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

# Templates that should have the Related Architecture Decisions section
APPLICABLE_TEMPLATES = [
    "architecture-vision.md",
    "business-architecture.md",
    "data-architecture.md",
    "application-architecture.md",
    "technology-architecture.md",
    "gap-analysis.md",
    "architecture-roadmap.md",
    "statement-of-architecture-work.md",
    "migration-plan.md",
    "compliance-assessment.md",
    "requirements-register.md",
    "engagement-charter.md",
    "governance-framework.md",
    "implementation-governance-plan.md",
]

RELATED_ADRS_SECTION = """\
## Related Architecture Decisions

<details>
<summary>📋 Guidance</summary>

List ADRs that informed, were informed by, or are otherwise relevant to this artifact.
Reference the ADR-NNN ID so readers can navigate to the full decision record.
Use `/ea-adrs` to manage the ADR Register and surface ADR summaries.

When a significant decision is made during an interview for this artifact, the
`ea-interviewer` will suggest creating an ADR if the decision meets the threshold
criteria (technology/vendor selection, high cost/risk, hard to reverse, etc.).

</details>

| ADR ID | Title | Status | Summary |
|---|---|---|---|
| *(no related ADRs recorded)* | — | — | — |

---

"""

def has_related_adrs_section(content: str) -> bool:
    return "## Related Architecture Decisions" in content

def find_insertion_point(content: str) -> int:
    """
    Find the line index at which to insert the Related ADRs section.
    Preference order:
      1. Before '## Appendix A3'
      2. Before '## Appendix A4'
      3. Before the last '---' separator line (footer)
      4. End of file
    """
    lines = content.splitlines(keepends=True)

    for i, line in enumerate(lines):
        if line.strip().startswith("## Appendix A3"):
            return i
        if line.strip().startswith("## Appendix A4"):
            return i

    # Look for a trailing footer line (e.g. "*Use `/ea-..." or "*Generated by...")
    for i in range(len(lines) - 1, -1, -1):
        stripped = lines[i].strip()
        if stripped.startswith("*Use") or stripped.startswith("*Generated"):
            return i

    # Last '---' separator
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip() == "---":
            return i + 1

    return len(lines)

def insert_section(content: str, section: str, insertion_index: int) -> str:
    lines = content.splitlines(keepends=True)
    lines.insert(insertion_index, section)
    return "".join(lines)

def process_template(path: Path, dry_run: bool) -> str:
    """Process one template file. Returns status string."""
    content = path.read_text(encoding="utf-8")

    if has_related_adrs_section(content):
        return f"  SKIP   {path.name} — section already present"

    insertion_index = find_insertion_point(content)
    new_content = insert_section(content, RELATED_ADRS_SECTION, insertion_index)

    if dry_run:
        return f"  DRY    {path.name} — would insert at line {insertion_index + 1}"

    path.write_text(new_content, encoding="utf-8")
    return f"  ADDED  {path.name} — inserted at line {insertion_index + 1}"

def main():
    dry_run = "--dry-run" in sys.argv

    if dry_run:
        print("DRY RUN — no files will be modified\n")

    missing = []
    results = []

    for filename in APPLICABLE_TEMPLATES:
        path = TEMPLATES_DIR / filename
        if not path.exists():
            missing.append(filename)
            results.append(f"  MISS   {filename} — file not found")
            continue
        results.append(process_template(path, dry_run))

    print(f"add-related-adrs.py — processing {len(APPLICABLE_TEMPLATES)} templates\n")
    for r in results:
        print(r)

    added = sum(1 for r in results if r.startswith("  ADDED"))
    skipped = sum(1 for r in results if r.startswith("  SKIP"))
    dry_count = sum(1 for r in results if r.startswith("  DRY"))

    print()
    if dry_run:
        print(f"Summary: {dry_count} would be added, {skipped} already have the section, {len(missing)} not found")
    else:
        print(f"Summary: {added} updated, {skipped} already compliant, {len(missing)} not found")

    if missing:
        print(f"\nMissing files: {', '.join(missing)}")

if __name__ == "__main__":
    main()
